#!/bin/bash

if [[ -z "$SHED_CONFIG_FILE" ]]; then
    echo 'SHED_CONFIG_FILE is not set.' >&2
    exit 1
fi

if [[ -f "$SHED_CONFIG_FILE" ]]; then
    echo "Shed Config already exist ($SHED_CONFIG_FILE)." >&2
    exit 2
fi

SHED_CONFIG_FILE_SAMPLE=/usr/share/shed/config.yaml.sample

cp "$SHED_CONFIG_FILE_SAMPLE" "$SHED_CONFIG_FILE"
