#!/bin/bash

readonly COMPONENT_NAME=siakhooi-shed

if command -v apt >/dev/null 2>&1; then
  apt show "$COMPONENT_NAME" 2>/dev/null | grep 'Version:' | sed 's/Version: //'
else
  echo "apt not found." >&2
  exit 1
fi