#!/bin/bash

export SHED_VERSION=1.15.0
export SHED_CONFIG_HOME="${SHED_CONFIG_HOME:-$HOME/.shed}"
export SHED_CONFIG_FILE=${SHED_CONFIG_HOME}/config.yaml
export SHED_CONFIG_DIRECTORY_RESOURCES=$SHED_CONFIG_HOME/kubectl-resources

[[ -d "$SHED_CONFIG_HOME" ]] || mkdir -p "$SHED_CONFIG_HOME"
[[ -f "$SHED_CONFIG_FILE" ]] || /usr/lib/shed/shed-config-create-sample

SHED_SYSTEM_INIT_DIRECTORY=/usr/lib/shed/init.d/shed-init

if [[ -d $SHED_SYSTEM_INIT_DIRECTORY ]]; then
    for f1 in $(find "$SHED_SYSTEM_INIT_DIRECTORY" -type f | sort); do
        # shellcheck source=/dev/null
        source "$f1"
    done
fi

SHED_USER_INIT_DIRECTORY=$SHED_CONFIG_HOME/init.d/shed-init

if [[ -d $SHED_USER_INIT_DIRECTORY ]]; then
    for f1 in $(find "$SHED_USER_INIT_DIRECTORY" -type f | sort); do
        # shellcheck source=/dev/null
        source "$f1"
    done
fi

# shellcheck source=/dev/null
source /usr/lib/shed/shed-init_shed-use
