#!/bin/bash

_shed_check_variable_if_set_shed_config_file() {
    if [[ -z "$SHED_CONFIG_FILE" ]]; then
        echo 'SHED_CONFIG_FILE is not set.' >&2
        exit 1
    fi
}
_shed_check_file_if_exists_shed_config_file() {
  if [ ! -f "$SHED_CONFIG_FILE" ]; then
    echo "SHED_CONFIG_FILE does not exist. (value: $SHED_CONFIG_FILE)" >&2
    exit 2
  fi
}
_shed_check_variable_if_set_shed_code() {
  if [[ -z "$SHED_CODE" ]]; then
    echo 'SHED_CODE is not set.' >&2
    exit 3
  fi
}

