#!/bin/bash

command -v yq >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[1;31mError: yq not found![0m please install at [1;31mhttps://github.com/mikefarah/yq[0m." >&2
fi
command -v kubectl >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[1;31mError: kubectl not found![0m please install at [1;31mhttps://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[0m." >&2
fi
command -v helm >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[1;31mWarning: helm not found![0m if you want to use helm feature, please install at [1;31mhttps://helm.sh/docs/intro/install/[0m." >&2
fi
command -v istioctl >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[1;31mWarning: istioctl not found![0m if you want to use istioctl feature, please install at [1;31mhttps://istio.io/latest/docs/setup/getting-started/[0m." >&2
fi

cat <<___EOF___

Add the following line to your [1;32m~/.bashrc[0m file and restart your shell to use shed!
  [1;32msource /usr/lib/shed/shed-init[0m

after that, run the follow command to edit your shed config:
  [1;32mshed-config-edit[0m

___EOF___
