shed-env:
	shed-env

shed-list-code:
	shed-list-code

shed-list:
	shed-list

shed-config:
	shed-config

shed-config-get:
	shed-config-get .shed-init.shed
	shed-config-get .sheds[0].code
	shed-config-get .sheds[0].name
	shed-config-get .sheds[1].code
	shed-config-get .sheds[1].name

shed-config-edit:
	shed-config-edit
	:q!

shed-values:
	shed-use T
	shed-values
	shed-use D
	shed-values

shed-value:
	shed-use T
	shed-value .code
	shed-value .name
	shed-use D
	shed-value .code
	shed-value .name
