name: Build shed-tester:ubuntu

on: 
  workflow_dispatch:
  workflow_call:
      secrets:
        REGISTRY_PASSWORD_DOCKER:
          required: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          username: siakhooi
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./test
          file: ./test/Dockerfiles/Dockerfile_ubuntu
          push: true
          tags: siakhooi/shed-tester:ubuntu
