name: Test-Ubuntu

on: workflow_call

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: deliverables
          path: ./
      - run: ./.github/bin/test-ubuntu.sh
      - uses: actions/upload-artifact@v4
        with:
          name: test-result-ubuntu
          path: ./test/actual-tests
