name: Bats Test-Ubuntu

on: workflow_call

jobs:
  bats-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: deliverables
          path: ./
      - run: ./tests/bin/docker-run-bats-test-ubuntu.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bats-test-result-ubuntu
          path: ./tests/bats-test-result-*.log
