name: On New Release
on:
  release:
    types: [created]

jobs:
  quality-build-test:
    uses: ./.github/workflows/workflow-new-code-changes.yml
  deploy-all:
    needs: quality-build-test
    uses: ./.github/workflows/workflow-deploy-all.yml
