name: On New Code Changes
on:
  workflow_call:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: ./.github/workflows/quality-shellcheck.yml
  build:
    needs: quality
    uses: ./.github/workflows/build-deb-file.yml
  test:
    needs: build
    uses: ./.github/workflows/workflow-run-all-tests.yml
