name: Deploy all artifacts

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true
      PUBLISH_TO_GITHUB_REPO_TOKEN:
        required: true

jobs:
  release-assets:
    uses: ./.github/workflows/deploy-github-release-assets.yml
    secrets:
      TOKEN_TO_UPLOAD_ASSETS: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
  siakhooi-apt:
    uses: ./.github/workflows/publish-to-siakhooi-apt.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
