name: Build and Test on Push
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: ./.github/workflows/quality-shellcheck.yml
  build:
    needs: quality
    uses: ./.github/workflows/build-deb-file.yml
  test-ubuntu:
    needs: build
    uses: ./.github/workflows/test-with-ubuntu.yml
  test-debian:
    needs: build
    uses: ./.github/workflows/test-with-debian.yml
  bats-test-debian:
    needs: build
    uses: ./.github/workflows/test-with-bats-debian.yml
  bats-test-ubuntu:
    needs: build
    uses: ./.github/workflows/test-with-bats-ubuntu.yml
