#!/bin/bash

load_kubectl_config=$(shed-config-get .shed-init.load-kubectl-config)

if ! is-false "$load_kubectl_config"; then

    if [[ -z $KUBECONFIG ]]; then
        SHED_KUBECONFIG_PATH=$SHED_CONFIG_HOME/kubectl-config

        if [[ -d $SHED_KUBECONFIG_PATH ]]; then
            if [ "$(ls -A "$SHED_KUBECONFIG_PATH" 2>/dev/null)" ]; then
                KUBECONFIG=$HOME/.kube/config

                for f in $(find "$SHED_KUBECONFIG_PATH" -type f | sort); do
                    KUBECONFIG="$KUBECONFIG:$f"
                done

                export KUBECONFIG
            fi
        fi
    fi

fi
