#!/bin/bash

function shed-current-context() {
  local R=""
  if [[ -n "$SHED_CODE" ]]; then
    if [[ -n "$SHED_KUBECONFIG_NUMBER" ]]; then
      local context namespace
      context=$(shed-value ".kubeconfig[$SHED_KUBECONFIG_NUMBER].context")
      namespace=$(shed-value ".kubeconfig[$SHED_KUBECONFIG_NUMBER].namespace")
      promptname=$(shed-value ".kubeconfig[$SHED_KUBECONFIG_NUMBER].prompt-name")

      if [[ -n "$promptname" ]]; then
        R="[$SHED_CODE/$promptname]"
      else
        if [[ -n "$context" ]]; then
          if [[ -n "$namespace" ]]; then
            R="[$SHED_CODE/$context/$namespace]"
          else
            R="[$SHED_CODE/$context]"
          fi
        fi
      fi
    else
      R="[$SHED_CODE]"
    fi
  fi
  echo.yellow -n "$R"
}

export PS1="\[\e[01;32m\]\u@\h\[\e[0m\]:\$(shed-current-context)\[\e[01;34m\]\w\[\e[0m\]\$ "
