#!/bin/bash

alias k='shed-kubectl'
alias k-sh='shed-kubectl-exec-sh'
alias k-bash='shed-kubectl-exec-bash'
alias k-scale='shed-kubectl-scale'

if [[ $(type -t __start_kubectl) == function ]]; then

  ## modify from command: kubectl completion bash
  if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_kubectl shed-kubectl
    complete -o default -F __start_kubectl k
  else
    complete -o default -o nospace -F __start_kubectl shed-kubectl
    complete -o default -o nospace -F __start_kubectl k
  fi
fi
