#!/bin/bash

alias i='shed-istioctl'

if [[ $(type -t __start_istioctl) == function ]]; then

  ## modify from command: istioctl completion bash
  if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_istioctl shed-istioctl
    complete -o default -F __start_istioctl i
  else
    complete -o default -o nospace -F __start_istioctl shed-istioctl
    complete -o default -o nospace -F __start_istioctl i
  fi
fi
